### ISSUE TITLE
Add cards of plants 

### ISSUE THREAD

**Issue by oninbo** [LinaChasova/Plants.vs.Zombies#7]
For the player to choose which kind of plant to plant

**Comment by LinaChasova** [comment]
![cardblock](https://user-images.githubusercontent.com/24250521/54273556-31d60a80-4597-11e9-9341-5c45d5c5ddfb.png)
![peasshootercard](https://user-images.githubusercontent.com/24250521/54273575-38fd1880-4597-11e9-9b36-0b70e90cfd08.png)
![sunflowercard](https://user-images.githubusercontent.com/24250521/54273580-3bf80900-4597-11e9-8c04-2793fb67f8cb.png)
